import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import Header from "./components/header";
import Footer from "./components/footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shoopy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="min-h-screen dark:bg-slate-500">
        <h1 className="text-center text-6xl font-bold p-4">Welcome to Shoopy</h1>
      </main>
      <Footer />
    </>
  );
};

export default Home;
